# netlify.toml

# Specify build settings
[build]
  publish = "dist"
  command = "npm run docs:build"

# Define redirects
[[redirects]] 
  from = "/" 
  to = "/en" 
  status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
